### ISSUE TITLE
Question: comparison to geoserver?

### ISSUE THREAD

**Issue by 7yl4r** [nasa-gibs/onearth#93]
Forgive my ignorance here, but I am wondering: how does gibs/onearth compare with geoserver? 

Is development here driven by something geoserver lacks or is there a more fundamental difference?

**Comment by jtroberts** [comment]
OnEarth is mainly driven by the need for high performance, time-dynamic, tiled web map services. Unlike GeoServer, OnEarth does not focus on supporting a broad spectrum of OGC standards and file formats. (However, MapServer is included for convenience to provide non-tiled services such as WMS.) MRF is the core file format used for storage due to its performance benefits. OnEarth also uses low-level Apache modules written in C to achieve low overhead for performance. The handling of large-scale, geospatial data layers with variable time coverage (e.g. daily/weekly/monthly satellite products) is a major feature of OnEarth that is generally lacking in other software. OnEarth v2 migrates to using container-managed services for cloud environments.

**Comment by 7yl4r** [comment]
Thank you for your detailed and quick response!

You have answered all of my questions and more so I will close this. 
It might be nice to have some of that great info in the readme.
